### ISSUE TITLE
Post event things

### ISSUE THREAD

**Issue by Manan-dev** [volhacks/volhacks.github.io#156]

**Comment by Manan-dev** [comment]
These are all the changes I can think of, let me know if I should start working on these if they are correct and add it to the list other changes you guys need.

1. remove check in form link
2. remove register, devpost button
3. change previous season's website to this year's.
4. remove date of the event
5. change "Volhacks V" to "Volhacks VI"
6. put the sponsors button on again
7. make schedule times and location to TBA 
8. remove dates of volhacks V from faq card 
9. remove halloween card
10. change the date at the bottom of the page to 2022
11. remove mlh logo

**Comment by andreicozma1** [comment]
> These are all the changes I can think of, let me know if I should start working on these if they are correct and add it to the list other changes you guys need.
> 
> 1. remove check in form link
> 2. remove register, devpost button
> 3. change previous season's website to this year's.
> 4. remove date of the event
> 5. change "Volhacks V" to "Volhacks VI"
> 6. put the sponsors button on again
> 7. make schedule times and location to TBA
> 8. remove dates of volhacks V from faq card
> 9. remove halloween card
> 10. change the date at the bottom of the page to 2022
> 11. remove mlh logo

everything looks good!
A few suggestions:
- we could leave VolHacks V and for the devpost we could say View Submissions
- leave the date but say something like "Thank you to everyone who participated on<br>October 29th - 31st, 2021"
- we can leave the MLH logo on there
- sponsor button just leave it commented, we'll re-add it later on for the next season
@Manan-dev
