### ISSUE TITLE
TRACKER: MLH Website Requirements

### ISSUE THREAD

**Issue by andreicozma1** [volhacks/volhacks.github.io#81]
@Manan-dev as part of MLH website suggestions and requirements, they have provided us this link:
https://guide.mlh.io/in-person-hackathons/putting-together-your-hackathon-website/updating-website-with-day-of-information

Could you in the comments list how we stand on these and if there's anything you see that is important and we might need to add?
CC: @hunterprice04

**Comment by Manan-dev** [comment]
1. Finish Schedule as we approach the event
2. Link our slack
3. They recommend adding prizes, sponsors and different themes info

**Comment by andreicozma1** [comment]
@Manan-dev
sounds great, could you create an issue to track schedule updates? As well as for tracking new sponsor stuff. These two will be an ongoing thing with probably multiple PR's as updates become available for each.
Slack - we already have the slack linked, right?
Prizes & Themes - where do you think we could add these?

CC: @hunterprice04

**Comment by Manan-dev** [comment]
Ahh yes, I forgot slack was linked but as we get closer to event, I suggest we make it more obvious so they know to join it.
I want to see some hackathon websites to get some ideas of where to put prizes and themes and even if we should or not.
so if you have any in mind, then recommend me some websites please.

**Comment by andreicozma1** [comment]
Agreed about the button. And yeah, let's look into some other hackathons websites. I'll keep a list here

**Comment by andreicozma1** [comment]
TODO: Add the MLH Season 2022 banner back to where the previous banner was

**Comment by Manan-dev** [comment]
added
